[tool.poetry]
name = "pystk2-gymnasium"
version = "0.3.2"
description = "Gymnasium wrapper for PySTK2"
authors = ["Benjamin Piwowarski <benjamin@piwowarski.fr>"]
license = "GPL"
readme = "README.md"

homepage = "https://github.com/bpiwowar/pystk2-gymnasium"
repository = "https://github.com/bpiwowar/pystk2-gymnasium"

[tool.poetry.dependencies]
python = "^3.8"
PySuperTuxKart2 = "=0.3.4"
gymnasium = ">0.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
